### ISSUE TITLE
[?] Gather usage stats and app errors

### ISSUE THREAD

**Issue by marekrogala** [Appsilon/wildlife-explorer#10]
Gather statistics about app usage. 

We need this to be able to show that app is having active users and to measure if it is being used, and gather info to improve the app.

User should be informed about this during installation.
Stats should be submitted regularly when user has an internet connection, and when there is no internet connection they should be collected and submitted to a server when connection is restored.

Determine what to collect specifically.

Ideally, we should also submit information about app crashes and errors.

**Comment by filipstachura** [comment]
My idea is to collect usage data through Redux middleware. [Redux-beacon](https://github.com/rangle/redux-beacon) can be the main thing - it has support for both google analytics and offline mode (it uses [IndexedDB API](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) underneath which seems like a sound choice).

Please let me know if this is the way you want to move forward.

I also feel that cleaning repo first would simplify my work here (e.g. remove hanging boilerplate code).

**Comment by filipstachura** [comment]
Draft of what I have in mind: https://github.com/Appsilon/wildlife-explorer/blob/0a99259ad977b870fb9c36af9d1052f4d3bbcb88/app/store/analyticsMiddleware.ts

**Comment by marekrogala** [comment]
sounds perfect if it can support an Electron app!

**Comment by marekrogala** [comment]
one note: how will we identify users/installations?

**Comment by filipstachura** [comment]
It says that Client ID is unique for every machine.

**Comment by filipstachura** [comment]
Current version seems to submit online/offline mode (through Redux states). It seems to work pretty good.

We also have **basic support for app errors.**

### TODO
- [ ] User should be informed about this during installation.
- [ ] Determine what to collect specifically.
