### ISSUE TITLE
Allow users to correct classified labels and export a modified CSV

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/wildlife-explorer#135]
In the observations explorer (opened by clicking images displayed over the map), the user should be able to override the top prediction by selecting one of the available classes or providing a custom one.

The user should then have an option to export a CSV file with modified predictions. The exported CSV should have the following columns modified:
* common_name: custom prediction
* taxon columns: matched from taxons.csv or empty if not available
* uncertainty: 1
* identified_by: user

**Comment by rcwhytock** [comment]
@kamilzyla Just to clarify - you are correct that we want to allow users to correct classified species labels and export the modified csv. We don't need to change image IDs. thanks

**Comment by kamilzyla** [comment]
@rcwhytock Thanks Robbie for clarification!
