### ISSUE TITLE
[4h?] Classify page: Run ML model on sample images dataset

### ISSUE THREAD

**Issue by tadeuszbaraslupski** [Appsilon/wildlife-explorer#4]
# Acceptance criteria
- [x] Make sure that the actual Serengeti model is ran on images from the provided folder in dev version and that a correct output is produced, in the same format as used in #5 .
- [x] test this on test images dataset from Robbie
- [x] progress should be displayed correctly and be informative, and the entire flow needs to be helpful to non-technical user
- [x] test Explore page and resolve any issues in Explore page that show up or create issues for them
- [ ] show error if models runner or model files are not present - inform that they need to unpack models in the application directory

**Comment by marekrogala** [comment]
@kamilzyla I think we've actually already started this yesterday, so I think this may be quick and it's good to finalize this task

**Comment by kamilzyla** [comment]
I marked "test this on test images dataset from Robbie" as done. There were problems with classifier dying on my machine sometimes but it is now tracked in #74.

**Comment by kamilzyla** [comment]
The last point, "show error if models runner or model files are not present" will be better tracked in issue #47; I'll close this issue.
