### ISSUE TITLE
[2h] Explore page: Add a toggle that applies a certainty threshold filter to results.

### ISSUE THREAD

**Issue by marekrogala** [Appsilon/wildlife-explorer#67]
1. Add a toggle in the filters area saying ">= X% certainty" (X to be defined)
2. if toggle is enabled, consider non blank images with score_1 < X as blank

**Comment by swiezew** [comment]
In the paper we are currently using  X=0.7, so that's what I recommend.

**Comment by kamilzyla** [comment]
Already resolved.
