### ISSUE TITLE
Explore page: Show all observations and not first 100

### ISSUE THREAD

**Issue by marekrogala** [Appsilon/wildlife-explorer#76]
We have limited the results to first 100 in development, but before release we should fix this and make sure it all works with a large (~30K) number of photos

**Comment by kamilzyla** [comment]
I have removed the limit for now (PR #82). Observations are now grouped based on the station ID, so we will display at most as many markers as there are stations. Still, our list currently has about 7700 stations, so it is probably too much to display for large datasets.

I think a proper solution would be to limit the number of displayed markers to N most relevant (Most observed species? Most observations? N ~ 100) in the current map view and update it as the user drags / zooms the map. What do you think @marekrogala?

**Comment by marekrogala** [comment]
I think we should check if the map can handle all ~8000 markers, perhaps this is fine?
Also, can all the rest of the page handle ~30000 observations?

**Comment by marekrogala** [comment]
I've tested with 30K observations, main explore page works perfectly fine. (A bigger issue will be inference time with 30K photos on a slow machine, inference for 600 photos took 10 mins on my machine. But this can be much faster if the photos are smaller).
Stations with thousands of photos may not show or work very slowly - we can add a limit or pagination there later if this becomes an issue.
7700 stations may be too much for the map to handle, but I haven't tested this. Let's see if this becomes an issue.
